"""
seed_properties.py — Sample Pune property data
Run via API:  GET  http://localhost:8000/properties/seed-data/run
Or directly:  python seed_properties.py
"""

PROPERTIES = [
    {
        "property_id":   "prop_001",
        "title":         "2 BHK Flat in Wakad",
        "location":      "Wakad, Pune",
        "latitude":      18.5913,
        "longitude":     73.7632,
        "price":         6500000,
        "price_display": "₹65 Lakh",
        "property_type": "2BHK",
        "bedrooms":      2,
        "size_sqft":     980,
        "amenities":     ["Gym", "Swimming Pool", "Clubhouse", "24/7 Security"],
        "description":   "Spacious 2 BHK near Wakad Chowk with premium amenities. Zero brokerage on Brickfolio.",
        "image":         "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
        "builder":       "Kolte Patil",
        "possession":    "Dec 2025",
        "rera":          "P52100047739",
        "badge":         "Ready to Move",
        "featured":      True,
    },
    {
        "property_id":   "prop_002",
        "title":         "2 BHK Flat in Hinjewadi",
        "location":      "Hinjewadi Phase 1, Pune",
        "latitude":      18.5912,
        "longitude":     73.7388,
        "price":         7200000,
        "price_display": "₹72 Lakh",
        "property_type": "2BHK",
        "bedrooms":      2,
        "size_sqft":     1050,
        "amenities":     ["Gym", "Terrace Garden", "EV Charging", "Coworking Space"],
        "description":   "IT hub location — walk to Infosys & Wipro campuses. Zero brokerage.",
        "image":         "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80",
        "builder":       "Godrej Properties",
        "possession":    "Mar 2026",
        "rera":          "P52100049001",
        "badge":         "New Launch",
        "featured":      True,
    },
    {
        "property_id":   "prop_003",
        "title":         "3 BHK Premium Flat in Baner",
        "location":      "Baner, Pune",
        "latitude":      18.5592,
        "longitude":     73.7888,
        "price":         12500000,
        "price_display": "₹1.25 Cr",
        "property_type": "3BHK",
        "bedrooms":      3,
        "size_sqft":     1580,
        "amenities":     ["Rooftop Pool", "Gym", "Concierge", "Smart Home", "Power Backup"],
        "description":   "Ultra-luxury 3 BHK in the heart of Baner's tech corridor. Zero brokerage.",
        "image":         "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
        "builder":       "Panchshil Realty",
        "possession":    "Jun 2026",
        "rera":          "P52100048500",
        "badge":         "Luxury",
        "featured":      True,
    },
    {
        "property_id":   "prop_004",
        "title":         "3 BHK Flat in Balewadi",
        "location":      "Balewadi, Pune",
        "latitude":      18.5776,
        "longitude":     73.7787,
        "price":         10800000,
        "price_display": "₹1.08 Cr",
        "property_type": "3BHK",
        "bedrooms":      3,
        "size_sqft":     1420,
        "amenities":     ["Sports Complex", "Gym", "Kids Play Area", "Covered Parking"],
        "description":   "Near Balewadi Sports Complex. Premium 3 BHK with modern finishes.",
        "image":         "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
        "builder":       "Paranjape Schemes",
        "possession":    "Sep 2025",
        "rera":          "P52100046200",
        "badge":         "Ready to Move",
        "featured":      False,
    },
    {
        "property_id":   "prop_005",
        "title":         "4 BHK Villa in Kharadi",
        "location":      "Kharadi, Pune",
        "latitude":      18.5578,
        "longitude":     73.9447,
        "price":         28000000,
        "price_display": "₹2.8 Cr",
        "property_type": "Villa",
        "bedrooms":      4,
        "size_sqft":     3200,
        "amenities":     ["Private Pool", "Garden", "Home Theater", "3-Car Garage", "Solar Panels"],
        "description":   "Exclusive gated villa community near EON IT Park. Zero brokerage.",
        "image":         "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
        "builder":       "Kumar Properties",
        "possession":    "Ready",
        "rera":          "P52100045800",
        "badge":         "Premium Villa",
        "featured":      True,
    },
    {
        "property_id":   "prop_006",
        "title":         "Studio Apartment in Viman Nagar",
        "location":      "Viman Nagar, Pune",
        "latitude":      18.5665,
        "longitude":     73.9138,
        "price":         4200000,
        "price_display": "₹42 Lakh",
        "property_type": "Studio",
        "bedrooms":      1,
        "size_sqft":     520,
        "amenities":     ["Security", "Gym", "Laundry", "Café"],
        "description":   "Smart studio apartment near airport. Ideal for working professionals.",
        "image":         "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80",
        "builder":       "Rohan Builders",
        "possession":    "Ready",
        "rera":          "P52100044100",
        "badge":         "Investor Pick",
        "featured":      False,
    },
    {
        "property_id":   "prop_007",
        "title":         "2 BHK Flat in Aundh",
        "location":      "Aundh, Pune",
        "latitude":      18.5626,
        "longitude":     73.8079,
        "price":         8900000,
        "price_display": "₹89 Lakh",
        "property_type": "2BHK",
        "bedrooms":      2,
        "size_sqft":     1100,
        "amenities":     ["Gym", "Garden", "Security", "Visitor Parking"],
        "description":   "Prime Aundh location, minutes from FC Road and D-Mart.",
        "image":         "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&q=80",
        "builder":       "Bhosale Group",
        "possession":    "Ready",
        "rera":          "P52100043900",
        "badge":         "Best Seller",
        "featured":      False,
    },
    {
        "property_id":   "prop_008",
        "title":         "Residential Plot in Pimpri",
        "location":      "Pimpri, Pune",
        "latitude":      18.6298,
        "longitude":     73.7997,
        "price":         4500000,
        "price_display": "₹45 Lakh",
        "property_type": "Plot",
        "bedrooms":      0,
        "size_sqft":     1200,
        "amenities":     ["Gated Community", "24/7 Security", "Water Supply", "Road Access"],
        "description":   "PCMC-approved residential plot in fast-developing locality. High ROI potential.",
        "image":         "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80",
        "builder":       "N/A",
        "possession":    "Immediate",
        "rera":          "N/A",
        "badge":         "Plot",
        "featured":      False,
    },
    {
        "property_id":   "prop_009",
        "title":         "3 BHK in Kalyani Nagar",
        "location":      "Kalyani Nagar, Pune",
        "latitude":      18.5480,
        "longitude":     73.9049,
        "price":         16500000,
        "price_display": "₹1.65 Cr",
        "property_type": "3BHK",
        "bedrooms":      3,
        "size_sqft":     1850,
        "amenities":     ["Sky Terrace", "Pool", "Gym", "Concierge", "Club"],
        "description":   "Premium high-rise in Kalyani Nagar. Panoramic views, top finishes.",
        "image":         "https://images.unsplash.com/photo-1582407947304-fd86f28320c8?w=600&q=80",
        "builder":       "Sobha Limited",
        "possession":    "Dec 2025",
        "rera":          "P52100044800",
        "badge":         "Luxury",
        "featured":      True,
    },
    {
        "property_id":   "prop_010",
        "title":         "2 BHK Flat in Chinchwad",
        "location":      "Chinchwad, Pune",
        "latitude":      18.6486,
        "longitude":     73.8069,
        "price":         5800000,
        "price_display": "₹58 Lakh",
        "property_type": "2BHK",
        "bedrooms":      2,
        "size_sqft":     925,
        "amenities":     ["Gym", "Security", "Covered Parking"],
        "description":   "Affordable 2 BHK near Chinchwad railway station. Excellent connectivity.",
        "image":         "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
        "builder":       "Vastushodh",
        "possession":    "Ready",
        "rera":          "P52100042100",
        "badge":         "Affordable",
        "featured":      False,
    },
    {
        "property_id":   "prop_011",
        "title":         "4 BHK Penthouse in Baner",
        "location":      "Baner Road, Pune",
        "latitude":      18.5630,
        "longitude":     73.7920,
        "price":         38000000,
        "price_display": "₹3.8 Cr",
        "property_type": "4BHK",
        "bedrooms":      4,
        "size_sqft":     4200,
        "amenities":     ["Private Terrace", "Jacuzzi", "Smart Home", "Concierge", "Wine Cellar"],
        "description":   "Sky penthouse with 360° views of Pune hills. Ultra-premium living redefined.",
        "image":         "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80",
        "builder":       "Panchshil Realty",
        "possession":    "Jun 2026",
        "rera":          "P52100048505",
        "badge":         "Penthouse",
        "featured":      True,
    },
    {
        "property_id":   "prop_012",
        "title":         "2 BHK in Wakad Phase 2",
        "location":      "Wakad, Pune",
        "latitude":      18.5944,
        "longitude":     73.7580,
        "price":         7100000,
        "price_display": "₹71 Lakh",
        "property_type": "2BHK",
        "bedrooms":      2,
        "size_sqft":     1020,
        "amenities":     ["Gym", "Pool", "Kids Area", "EV Charging"],
        "description":   "New project in Wakad with modern amenities. Zero brokerage only at Brickfolio.",
        "image":         "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=600&q=80",
        "builder":       "Kolte Patil",
        "possession":    "Sep 2026",
        "rera":          "P52100049200",
        "badge":         "New Launch",
        "featured":      False,
    },
    {
        "property_id":   "prop_013",
        "title":         "3 BHK in Hinjewadi Phase 3",
        "location":      "Hinjewadi Phase 3, Pune",
        "latitude":      18.5742,
        "longitude":     73.7112,
        "price":         9500000,
        "price_display": "₹95 Lakh",
        "property_type": "3BHK",
        "bedrooms":      3,
        "size_sqft":     1350,
        "amenities":     ["Tech Hub Proximity", "Gym", "Cafeteria", "Co-working Space"],
        "description":   "Steps from Meta & Accenture offices. Smart 3 BHK for tech professionals.",
        "image":         "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80",
        "builder":       "Godrej Properties",
        "possession":    "Mar 2026",
        "rera":          "P52100049003",
        "badge":         "Hot Property",
        "featured":      True,
    },
    {
        "property_id":   "prop_014",
        "title":         "1 BHK Flat in Kharadi",
        "location":      "Kharadi, Pune",
        "latitude":      18.5500,
        "longitude":     73.9400,
        "price":         4800000,
        "price_display": "₹48 Lakh",
        "property_type": "1BHK",
        "bedrooms":      1,
        "size_sqft":     620,
        "amenities":     ["Security", "Gym", "Covered Parking"],
        "description":   "Compact 1 BHK near EON IT Park. Perfect investment for young professionals.",
        "image":         "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
        "builder":       "Rohan Builders",
        "possession":    "Ready",
        "rera":          "P52100043800",
        "badge":         "Ready to Move",
        "featured":      False,
    },
    {
        "property_id":   "prop_015",
        "title":         "3 BHK Villa in Sus Road",
        "location":      "Sus Road, Pune",
        "latitude":      18.5741,
        "longitude":     73.7654,
        "price":         22000000,
        "price_display": "₹2.2 Cr",
        "property_type": "Villa",
        "bedrooms":      3,
        "size_sqft":     2800,
        "amenities":     ["Private Garden", "Pool", "3-Car Parking", "24/7 Security"],
        "description":   "Gated villa community near Sus. Serene green surroundings with top schools nearby.",
        "image":         "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80",
        "builder":       "Kumar Properties",
        "possession":    "Dec 2025",
        "rera":          "P52100045900",
        "badge":         "Limited Units",
        "featured":      False,
    },
    {
        "property_id":   "prop_016",
        "title":         "1 BHK in Pashan",
        "location":      "Pashan, Pune",
        "latitude":      18.5330,
        "longitude":     73.7990,
        "price":         3900000,
        "price_display": "₹39 Lakh",
        "property_type": "1BHK",
        "bedrooms":      1,
        "size_sqft":     570,
        "amenities":     ["Security", "Parking", "Garden"],
        "description":   "Budget-friendly 1 BHK in Pashan near NDA Road. Great rental yield.",
        "image":         "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80",
        "builder":       "Megapolis Builders",
        "possession":    "Ready",
        "rera":          "P52100041200",
        "badge":         "Affordable",
        "featured":      False,
    },
    {
        "property_id":   "prop_017",
        "title":         "2 BHK in Koregaon Park",
        "location":      "Koregaon Park, Pune",
        "latitude":      18.5362,
        "longitude":     73.8938,
        "price":         11500000,
        "price_display": "₹1.15 Cr",
        "property_type": "2BHK",
        "bedrooms":      2,
        "size_sqft":     1200,
        "amenities":     ["Pool", "Gym", "Club", "Valet Parking"],
        "description":   "Boutique 2 BHK in the heart of Pune's most premium neighbourhood.",
        "image":         "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=600&q=80",
        "builder":       "Nyati Group",
        "possession":    "Ready",
        "rera":          "P52100040800",
        "badge":         "Premium",
        "featured":      True,
    },
    {
        "property_id":   "prop_018",
        "title":         "Plot in Hadapsar",
        "location":      "Hadapsar, Pune",
        "latitude":      18.5024,
        "longitude":     73.9259,
        "price":         5200000,
        "price_display": "₹52 Lakh",
        "property_type": "Plot",
        "bedrooms":      0,
        "size_sqft":     1500,
        "amenities":     ["Gated Layout", "Wide Roads", "Electricity", "Water Connection"],
        "description":   "NA-approved plot near Magarpatta City. Ideal for self-construction.",
        "image":         "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80",
        "builder":       "N/A",
        "possession":    "Immediate",
        "rera":          "N/A",
        "badge":         "Plot",
        "featured":      False,
    },
    {
        "property_id":   "prop_019",
        "title":         "3 BHK in Shivajinagar",
        "location":      "Shivajinagar, Pune",
        "latitude":      18.5308,
        "longitude":     73.8474,
        "price":         14000000,
        "price_display": "₹1.4 Cr",
        "property_type": "3BHK",
        "bedrooms":      3,
        "size_sqft":     1680,
        "amenities":     ["Club", "Gym", "Security", "Power Backup", "Visitor Parking"],
        "description":   "Central Pune location. Steps from Pune University & FC Road.",
        "image":         "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=600&q=80",
        "builder":       "Pride Group",
        "possession":    "Ready",
        "rera":          "P52100039500",
        "badge":         "Best Seller",
        "featured":      False,
    },
    {
        "property_id":   "prop_020",
        "title":         "4 BHK in Viman Nagar",
        "location":      "Viman Nagar, Pune",
        "latitude":      18.5670,
        "longitude":     73.9145,
        "price":         19500000,
        "price_display": "₹1.95 Cr",
        "property_type": "4BHK",
        "bedrooms":      4,
        "size_sqft":     2400,
        "amenities":     ["Private Terrace", "Pool", "Gym", "Smart Home", "Concierge"],
        "description":   "Spacious 4 BHK near Phoenix Mall and Pune Airport. Top-tier finishes.",
        "image":         "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
        "builder":       "Kolte Patil",
        "possession":    "Jun 2026",
        "rera":          "P52100050100",
        "badge":         "New Launch",
        "featured":      True,
    },
]


# ── Run directly to seed the database ─────────────────────────────────────
if __name__ == "__main__":
    from database import db
    db.properties.drop()
    result = db.properties.insert_many(PROPERTIES)
    print(f"✅ Seeded {len(result.inserted_ids)} properties into MongoDB")